// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type SimpleheroDocumentDataSlicesSlice = SimpleHeroSlice;

/**
 * Content for SimpleHero documents
 */
interface SimpleheroDocumentData {
  /**
   * Slice Zone field in *SimpleHero*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: simplehero.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SimpleheroDocumentDataSlicesSlice>;
}

/**
 * SimpleHero document from Prismic
 *
 * - **API ID**: `simplehero`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SimpleheroDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SimpleheroDocumentData>,
    "simplehero",
    Lang
  >;

type TestDocumentDataSlicesSlice = HeroSliceSlice;

/**
 * Content for test documents
 */
interface TestDocumentData {
  /**
   * Slice Zone field in *test*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: test.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TestDocumentDataSlicesSlice> /**
   * Meta Description field in *test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: test.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *test*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: test.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TestDocumentData>, "test", Lang>;

export type AllDocumentTypes = SimpleheroDocument | TestDocument;

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * testRichText field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.testrichtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testrichtext: prismic.RichTextField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SimpleheroDocument,
      SimpleheroDocumentData,
      SimpleheroDocumentDataSlicesSlice,
      TestDocument,
      TestDocumentData,
      TestDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
    };
  }
}
